name = "mentoriumvk"
main = "index.js"
compatibility_date = "2026-05-10"



d1_databases = [
	{ binding = "DB", database_id = "6e88dbf6-de94-48fb-8e8b-c3f809e7f447", database_name = "mentoriumai" }
]
